IF NOT EXISTS(SELECT 1 FROM [Account].[Settings] WHERE [ID] = 'USERNAME_MINIMUM_LENGTH')
BEGIN
    INSERT INTO [Account].[settings] VALUES ('USERNAME_MINIMUM_LENGTH', 8)
END

IF NOT EXISTS(SELECT 1 FROM [Account].[Settings] WHERE [ID] = 'PASSWORD_MINIMUM_LENGTH')
BEGIN
    INSERT INTO [Account].[settings] VALUES ('PASSWORD_MINIMUM_LENGTH', 8)
END
